### ISSUE TITLE
Only show level when you look at mob not working on 1.20.1

### ISSUE THREAD

**Issue by MrKashew** [Daripher/Auto-Leveling#11]
![image](https://github.com/Daripher/Auto-Leveling/assets/53996665/0f16e272-ff79-413b-8c97-29f86715eb03)
![2023-07-10_17 32 33](https://github.com/Daripher/Auto-Leveling/assets/53996665/7ca12afa-98d1-451f-9e66-4220bc843905)

**Comment by ghost** [comment]
I also have this issue
