### ISSUE TITLE
Add Compatibility with Modded Dimensions starting Levels

### ISSUE THREAD

**Issue by SHXRKIEgg** [Daripher/Auto-Leveling#15]
Tried to change starting levels for modded dimensions with a datapack and they all still stay lvl 1.

The Datapack, works for vanilla dimensions 
[autoleveling.zip](https://github.com/Daripher/Auto-Leveling/files/12705964/autoleveling.zip)

**Comment by Daripher** [comment]
If these dimensions are from mods, they should be in a respective mod folder, not in minecraft folder

**Comment by SHXRKIEgg** [comment]
so I make a new folder called the_aether for example?

**Comment by Daripher** [comment]
Yes, same structure, but instead of minecraft folder it should be a mod folder
