### ISSUE TITLE
Allow setting levels to non-hostile creatures

### ISSUE THREAD

**Issue by ghost** [Daripher/Auto-Leveling#16]
whitelist = ["minecraft:horse"] or whitelist = ["minecraft:*"] doesn't make my dream come true. I want a high level horse to fight high level mobs. Any other horses work also. (PS: RIP Epona, one shot by a lv.84 skeleton...)

**Comment by Daripher** [comment]
This doesn't work because the mod was intended to only work with entities that have attack attribute.
I can expand the base list to all the living entities.

**Comment by ghost** [comment]
Thanks for the answer. 
- Can I edit the base list or add a non-hostile entity with a datapack or in the mod file ? How can I do this ?
- The levels would be interesting on the entities that we can tame (like the wolf !), not all entities. (I don't want a lvl.50 pig please)

**Comment by Daripher** [comment]
> * Can I edit the base list or add a non-hostile entity with a datapack or in the mod file ? How can I do this ?

Currently, you can not add entities that has no attack damage.
> * The levels would be interesting on the entities that we can tame (like the wolf !), not all entities.

I can leave the default list the same. Then I will allow users to add levels to passive mobs.

**Comment by ghost** [comment]
I agree, thanks for your work !

**Comment by ghost** [comment]
when the new version will be available ?.

**Comment by Daripher** [comment]
Soon
