### ISSUE TITLE
Per-dimension datapack configuration doesn't work

### ISSUE THREAD

**Issue by moonrushy** [Daripher/Auto-Leveling#2]
Hey, I created a datapack that tweaks the dimension settings that sets all mobs in the end to min level 50, but it just doesn't do anything.
The datapack itself seems to be ok, because I also added some entity-specific settings and they work just fine.
Tested this on 1.8 version of the mod for both 1.18.2 and 1.19.
<details> 
  <summary>.json content</summary>
   
![image](https://user-images.githubusercontent.com/43013386/184465659-d04d20ed-a530-4545-a8bd-10d0853f7b8e.png)

</details>
<details> 
  <summary>datapack .json path (just to be sure I'm not a complete moron and didn't screw it up)</summary>
   data\minecraft\leveling_settings\dimensions\the_end.json
</details>
<details> 
  <summary>in-game screenshot</summary>

![2022-08-13_05 22 08](https://user-images.githubusercontent.com/43013386/184465473-966f7284-0ca8-474f-944e-00c4b43cddad.png)
</details>

**Comment by Daripher** [comment]
Do you have settings for the enderman entity type?
Note that entity settings will always have higher priority over dimension settings.
If not, please provide **logs/latest.log** file after running the game.

**Comment by moonrushy** [comment]
No, I don't have any entity settings set for the enderman.
Here's the [latest.log](https://github.com/Daripher/Auto-Leveling/files/9331146/latest.log) taken on a fresh instance without any other mods just in case.
<details> 
  <summary>An in-game screen of entity settings working.</summary>
   
![2022-08-13_12 13 17](https://user-images.githubusercontent.com/43013386/184477357-e4efc0a6-1989-470e-adf6-c18f16def624.png)

</details>

Also, here's my datapack: [auto_level.zip](https://github.com/Daripher/Auto-Leveling/files/9331160/auto_level.zip)

**Comment by acertkojevs** [comment]
Hey, is this problem fixed?
I'm using the AutoLeveling-1.16.5-1.8.jar version and created a dackapack, but seems that on this version dimension level settings don't work.
