### ISSUE TITLE
Attribute modifiers config changes are not being saved

### ISSUE THREAD

**Issue by AetheriMC** [Daripher/Auto-Leveling#24]
Minecraft v1.20.1
Forge v47.2.4
Auto Leveling v1-20-1.19a

Issue: The attribute properties that are granted each time a creature levels are not respecting changes made to the config file. Instead, the attributes seem to go back to their default settings.

For example, minecraft:generic.attack_damage returns to its default setting of 0.1 no matter what the config says. This happens whether editing the config file directly or through the Configured mod.

It's uncertain as to whether changing the value has any impact on the server whatsoever. At first glance, reducing the generic damage attribute does seem to reduce mob damage (until server reset), but when summoning new creatures or using the /attribute command to read their modified damage attribute, there seems to be no change.

Thank you for your help!

**Comment by Daripher** [comment]
What happens if you spawn a new entity? Are they affected by correct attribute modifier value?
