### ISSUE TITLE
Server Attribute Config 1.20.1

### ISSUE THREAD

**Issue by Archer-Hellrose** [Daripher/Auto-Leveling#34]
I've been having a blast with your mod however i have come across an issue that i cant seem to figure out. I have a 1.20.1 Exaroton Private server my buddies and i play on with an MMO setting. The mod was working wonderfully with it until i found that most mobs at about level 30 run a mach speeds(Creepers are terrifying and enderman just have instant transmission speeds). So i tried to change the Attribute scale for speed but the setting just defaults. I did try using Configure and Forge Config Screens as well as in file with no luck. These did work in solo play though. am i missing something or can it just not be adjusted for servers. If it's not i would like to suggest adding  it in a future update.

**Comment by Daripher** [comment]
Try changing it manually in a config file

**Comment by Archer-Hellrose** [comment]
That's what i meant by in file. I apologize i should have phrased that differently.

**Comment by Archer-Hellrose** [comment]
I found the issue it was another mod had entity scaling it was Project MMO they were overlapping causing the attribute multipliers to stack. im sorry for any inconvenience i cause from this

**Comment by Archer-Hellrose** [comment]
Thanks for responding to my issue and i apologize for any inconvenience this may have caused.
