### ISSUE TITLE
1.19.2 Please add a global option for leveling.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Daripher/Auto-Leveling#5]
I am not smart enough to make a data pack. I have tried and I am starting to lose my mind. If you could as a skilled dev can you add a global or regional controller to what variables control mob levels? I know your using datapacks for full control but what if the only thing I need is a global modifier?

``starting_level

  Should always be higher than zero

 

max_level

  Should always be higher or equal to zero

  If set to zero, there will be no maximum level for mobs in this dimension

 

levels_per_distance

  Should always be higher or equal to zero

  How much levels mobs will gain per one block traveled from spawn

  Default value 0.01 means 1 level per 100 blocks traveled``
  
These functions ironically exist but not as a global variable and it is only for individual mobs which means I would have to not only copy paste things over 100 times since I have 100+ mobs but there is also no gaurentee I would do it right.

**Comment by Daripher** [comment]
If you want to change settings globally for each entity and each dimension, you only need to create settings for each dimension. Mod itself already contains all the files for dimensions, you just need to copy them and change the values you need.

**Comment by P3rf3ctXZer0** [comment]
Error what? Your still losing me ... I didn't see any generated files config aside from what I posed in either config or server config.

**Comment by Daripher** [comment]
You can make a datapack that only contains dimension settings. You don't have to create settings for each entity type if they all will be the same.

**Comment by P3rf3ctXZer0** [comment]
<- Not skilled at making data packs.

If you want to make me a template pack for your mod I am good at configuring things. I have issues in my brain I cannot explain that make certain tech steps difficult. I am not going to spend a week trying to do magic that would clearly take you 3 mins to do I just won't use this mod and I will wait for other options.

**Comment by Daripher** [comment]
I've made an example datapack for you. I hope it will help.
https://github.com/Daripher/Auto-Leveling/blob/1.19.2/src/test/example_leveling_settings.zip

**Comment by P3rf3ctXZer0** [comment]
I will try and learn it from here. Thank you for giving me starting blocks. This is exactly what I needed.

**Comment by Daripher** [comment]
I've added default leveling settings in the config in version 1.11

**Comment by AoSankaku** [comment]
For people seeking for modded dimension autoleveling modifications:

`datapacks/data/<modname>/leveling_settings/dimensions/<dimension_name>.json` will do the job. For instance, `datapacks/main/data/lostcities/leveling_settings/dimensions/lostcity.json` worked perfectly for me on 1.20.1 Forge
