### ISSUE TITLE
Incompatiblity with Immersive Portals(Forge)

### ISSUE THREAD

**Issue by Talan67** [Daripher/Auto-Leveling#6]
Minecraft version 1.18.2
Forge version 40.1.85
Auto Leveling version 1.11
Immersive Portals(Forge) version 1.4.12

Problem : When AL(Auto Leveling) and ImP(Immersive Portals) are loaded together mobs are unnaffected by the leveling system from AL in all dimensions.

Latest log: https://pastebin.com/NFgwChah

**Comment by Daripher** [comment]
Just tested and everything works. Make sure you don't have whitelist enabled, otherwise only whitelisted mobs will gain levels.

![image](https://user-images.githubusercontent.com/57239580/203695598-7e48f778-ccd8-40f0-9392-33b3124272c8.png)

**Comment by Talan67** [comment]
I should have been more specific, what I mean is they don't increase in level by distance or even the random bonus level option.

**Comment by Daripher** [comment]
I don't know what could cause that issue. Very strange.

**Comment by Talan67** [comment]
Ok have tested this a bit more, and its not as bad as I first thought. It seems to be the only thing that doesn't work is the level display, basically a mobs level still increases by distance but the level indicator does not reflect this, but there health and other attributes do.

**Comment by Daripher** [comment]
> Ok have tested this a bit more, and its not as bad as I first thought. It seems to be the only thing that doesn't work is the level display, basically a mobs level still increases by distance but the level indicator does not reflect this, but there health and other attributes do.

Yes, I know. For some reason, data is just not being synced. I've tested it myself and already talked to a Immersive Portals' developers, but they didn't answer yet.

**Comment by Daripher** [comment]
This should be fixed by Immersive Portals' devs. I've opened an issue in their repository.
https://github.com/iPortalTeam/ImmersivePortalsModForForge/issues/54
