### ISSUE TITLE
New update causes load time to increase by 15+ minutes

### ISSUE THREAD

**Issue by iron431** [Daripher/Auto-Leveling#7]
Upon updating this mod, my modpack began hanging for 15-20 minutes on startup (once the red Mojang screen loading bar reaches 100%). Upon reading the log, it seems to be something to do with texture atlas stitching, and coincidentally this new update brought custom mob textures based on level. I would love to play with this feature, but as of now I will be using the previous version.

**Comment by Daripher** [comment]
Can I have that modpack for testing? Also, can you provide more information? What version are you using?

**Comment by iron431** [comment]
[Lag test.zip](https://github.com/Daripher/Auto-Leveling/files/10145235/Lag.test.zip)
Game version: 1.18.2
Mod w/ Loading Issue: Latest (1.13)
Mod that works: 1.12

**Comment by Daripher** [comment]
Are you also using a texture pack?

**Comment by iron431** [comment]
I was not when testing
